version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mydb
    environment:
      MYSQL_DATABASE: "vip"
      MYSQL_ROOT_PASSWORD: "vip"
    ports:
      - 3305:3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: my-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql

volumes:
  mysql:
  redis_data: